Lambda-School-Labs/conference-contacts-fe

.gitignore, README.md, README.old.md, package-lock.json, package.json, public/index.html, public/manifest.json, public/robots.txt, src/App.css, src/App.js, src/App.test.js, src/index.css, src/index.js
=> app created/ with dependecnies installed

package.json, src/index.js
Adds Sentry exception monitoring
=> Added Sentry

.github/workflows/nodejs.yml
his will ensure our tests are passing on each push to maintain code quality.
=> add continuous integration

cypress.json, package-lock.json, package.json, public/index.html, src/queries/index.js
=> Bobbys branch

src/pages/profile.js
- [ x ] New feature (non-breaking change which adds functionality)
=> Profile delete alert

package-lock.json, package.json, src/pages/home.js, src/pages/profile.js
Added sections to display job title, location, tagline, bio and birthday on web profile page
Job title, location, tagline, bio and birthday were not displayed on web profile page
=> added profile info

src/pages/profile.js
- [ x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> ready to merge to staging

src/pages/profile.js
=> fixed typo

src/pages/home.js, src/pages/profile-edit.js, src/pages/profile.js, src/styles/index.css, tailwind.config.js
=> fixed home and profile spacing

src/containers/navbar.js, src/pages/home.js, src/pages/profile.js
Took out static features
Bug fix
=> removed static components

src/components/SocialLinks/SocialIcons/SVGIcon.js, src/components/SocialLinks/SocialIcons/SocialIcons.js, src/pages/profile.js
fixed preferred contact text wasn't linking
style, and link logic of icon links.
=> Icon bug fixes

src/pages/contacts.js, src/queries/index.js
=> additional filters for contact search box

src/components/contactList.js, src/components/dropButton.js, src/components/navComponent.js, src/pages/contacts.js, src/queries/index.js, src/styles/index.css, tailwind.config.js
Sorting contacts
Added a sort button for contacts to sort by recent or a-z
New feature
- [] My code has been reviewed by at least one peer
=> Contacts sort

src/components/navComponent.js
- [ x ] New feature (non-breaking change which adds functionality)
=> Public profile route

src/App.js, src/components/PublicProfile/AddButton/AddButton.js, src/pages/home.js
=> Public button

src/components/profilelink.js
=> fixed alert rerendering

src/components/PublicProfile/profilelink.js
=> replaced alert with modal popup

src/components/Profile/map.js, src/pages/App/profile.js
=> map styleing change

src/components/Profile/map.js, src/pages/App/contacts.js, src/pages/App/profile.js
=> fixed contacts load

src/containers/navbar.js, src/pages/App/home.js, src/queries/index.js
Reverts Lambda-School-Labs/conference-contacts-fe#121
=> Revert "added username to user query and changed id to username for the url i…"

src/components/PublicProfile/profilelink.js, src/containers/navbar.js, src/queries/index.js
=> added username prompt

src/components/MainRouter/MainRouter.js, src/components/PublicProfile/PublicProfile.js, src/pages/App/home.js, src/queries/index.js
=> changes to mainrouter to fix public url

src/components/Contact/Notes.js, src/pages/App/contacts.js, src/pages/App/profile.js, src/queries/index.js
Created UI/functionality for notes and adding notes
User can add noted about a contact
- [x ] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update
- [x ] Complete, tested, ready to review and merge
- [x ] My code follows the style guidelines of this project
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
=> Christine adding notes

src/components/Contact/Events.js, src/pages/App/profile.js, src/queries/index.js
=> Updated connections to contain the event the people met at

src/queries/index.js
=> changes to public profile query

README.md, package-lock.json, package.json, src/components/Contact/Events.js, src/components/Contact/Notes.js, src/components/Home/notificationsComponent.js, src/components/Home/userInfo.js, src/components/Landing/TeamMemberInfo.js, src/components/Landing/teampage.js, src/components/Nav/navComponent.js, src/components/PublicProfile/PublicProfile.js, src/components/PublicProfile/profilelink.js, src/pages/App/profile-edit.js, src/pages/App/profile.js
Added cancel button and functionality. Styled forms for events and notes
Styling
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Complete, tested, ready to review and merge
- [x ] My code follows the style guidelines of this project
- [x ] My changes generate no new warnings
=> Styling fixes christine

src/components/PublicProfile/profilelink.js
=> fixed the copy button for sharing link

src/components/Contact/Events.js, src/components/Contact/Notes.js, src/pages/App/profile.js, src/queries/index.js
=> fixed the error on pending contacts

src/components/Contact/Events.js, src/components/Contact/Notes.js, src/components/Home/notificationsComponent.js, src/pages/App/profile.js, src/styles/custom-utilities.css
Added background color to notes and events
Style
- [x ] Complete, tested, ready to review and merge
- [x ] New and existing unit tests pass locally with my changes
=> Adding testing christine

src/components/Contact/Events.js, src/components/Contact/Notes.js, src/components/Home/notificationsComponent.js, src/pages/App/profile.js, src/styles/custom-utilities.css
Reverts Lambda-School-Labs/conference-contacts-fe#137
=> Revert "Adding testing christine"

src/components/Contact/Events.js, src/components/Contact/Notes.js, src/pages/App/profile.js, src/queries/index.js
Reverts Lambda-School-Labs/conference-contacts-fe#136
=> Revert "fixed the error on pending contacts"

cypress/integration/features.spec.js
=> fixed a typo in the cypress tests

src/App.js, src/components/Contact/Notes.js, src/components/Contact/dropButton.js, src/components/Home/userInfo.js, src/components/Landing/teampage.js, src/components/Nav/navComponent.js, src/components/PublicProfile/PublicProfile.js, src/components/PublicProfile/profilelink.js, src/containers/navbar.js, src/pages/App/home.js, src/pages/App/profile.js
Fixed a few terminal warnings. 
- [x ] Bug fix (non-breaking change which fixes an issue)
- 
- [x ] Complete, tested, ready to review and merge
- x[ ] My code follows the style guidelines of this project
- [x ] My changes generate no new warnings
=> fixed several warnings

cypress/integration/login.spec.js, src/pages/App/contacts.js, src/pages/App/profile.js
Added testing for app home and profile page and edit
Deleted console.log displaying user information
testing
-
- [x ] My code follows the style guidelines of this project
- [ x] New and existing unit tests pass locally with my changes
=> Christine testing

cypress/integration/contacts.spec.js, cypress/integration/profile.spec.js, cypress/support/commands.js, src/components/Nav/navComponent.js
added logout functionality to testing
added tests for contacts and broke out profile edit testing into its own file. 
Having to logout manually after test 
- [ x] My code follows the style guidelines of this project
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] New and existing unit tests pass locally with my changes
- x[ ] There are no merge conflicts
=> added testing for logout and profile edit and contacts

src/components/Nav/navComponent.js, src/pages/App/profile.js
Trying to fix bug on build in netlify. Deleted data-cy tags.
=> deleted data-cy tags
